apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-dev
  namespace: tracking-dev
  labels:
    app: tracking-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking-dev
  template:
    metadata:
      labels:
        app: tracking-dev
    spec:
      containers:
      - name: tracking-dev
        image: vapprtech/tracking:latest
        imagePullPolicy: Always
        ports:
        - name: https
          containerPort: 3000
